### ISSUE TITLE
Html to wml enhancements

### ISSUE THREAD

**Issue by ZonerZoner** [sergey-tihon/Clippit#12]
Hi Sergey

Could you please review and integrate this pull request https://github.com/EricWhiteDev/Open-Xml-PowerTools/pull/2/files into your code base as I stumbled upon the rem issue in fonts. I have the code already locally and have attached it here (no permissions to create branch/pull request). A new nuget packages would be awesome then. Maybe you can also check other pull requests over there to enhance the library

Thanks lot!

[Clippit.zip](https://github.com/sergey-tihon/Clippit/files/4525683/Clippit.zip)

**Comment by sergey-tihon** [comment]
> (no permissions to create branch/pull request)

What do you mean by `no permission`? this is public repo, you should be able  to fork it, do your changes and then propose PR.

> Could you please review and integrate this pull request

At the moment I do not have personal interest/need on PowerTools components except PreesentationBuilder. 
But I am happy to merge PRs (with some basic docs and tests) and release new version.

**Comment by ZonerZoner** [comment]
I just added pull request #13 Could you verify the changes please?
