### ISSUE TITLE
HtmlConverter: gaps between letters

### ISSUE THREAD

**Issue by ashahabov** [sergey-tihon/Clippit#22]
There is [**test.docx**](https://github.com/sergey-tihon/Clippit/files/6447323/test.docx) created from .pdf via [PDF Focus .NET](https://sautinsoft.com/products/pdf-focus/order.php) library:

![image](https://user-images.githubusercontent.com/5969304/117569126-bf0c3f80-b0cc-11eb-9e00-8b0c318ad6cf.png)

HtmlConverter's HTML outcome ([**test.html.zip**](https://github.com/sergey-tihon/Clippit/files/6447326/test.html.zip)) is:

![image](https://user-images.githubusercontent.com/5969304/117569161-00045400-b0cd-11eb-8777-95a2b545ef7f.png)

I think the reason of **gap between letters** is PDF Focus .NET put almost all letter into own <w:r>:

![image](https://user-images.githubusercontent.com/5969304/117569300-be27dd80-b0cd-11eb-851b-e20e80d0a4b4.png)

Anyway, I think it is a bug on our HtmlConverter side. Or is there some option to avoid such result?

**Comment by sergey-tihon** [comment]
Sorry, I do not personally use HtmlConverter.
I believe that it is perfectly fine that word contains a ton of `run`s and it is ok that converter transform each `run` in `span`.

Looks like HTML/CSS issue - https://stackoverflow.com/questions/5078239/how-do-i-remove-the-space-between-inline-inline-block-elements

As workaround we can generate HTML without formatting and newline

instead of
```xml
      <p
        dir="ltr"
        class="pt-000000">
        <span
          class="pt-000001">ART</span>
        <span
          class="pt-000001">I</span>
        <span
          class="pt-000001">CLE</span>
      </p>
```

generate 

```xml
      <p dir="ltr" class="pt-000000"><span class="pt-000001">ART</span><span class="pt-000001">I</span><span class="pt-000001">CLE</span></p>
```


_p.s. I also see a lot of PR related to HtmlConverter - https://github.com/EricWhiteDev/Open-Xml-PowerTools/pulls (there is a chance that fix may be already there)_

**Comment by ashahabov** [comment]
Thank you for the quick answer!

After some investigation, I just re-used code from [WmlToHtmlConverter01](https://github.com/sergey-tihon/Clippit/blob/master/OpenXmlPowerToolsExamples/WmlToHtmlConverter01/WmlToHtmlConverter01.cs#L43) project and it works :)

Here is the code with correct output:
```C#
string docxPath = @"test.docx";
string htmlPath = @"test.html";

using WordprocessingDocument wDoc = WordprocessingDocument.Open(docxPath, true);
WmlToHtmlConverterSettings wmlToHtmlSetting = new ()
{
    CssClassPrefix = "pt-",
};
XElement htmlElement = WmlToHtmlConverter.ConvertToHtml(wDoc, wmlToHtmlSetting);

var html = new XDocument(
    new XDocumentType("html", null, null, null),
    htmlElement);

var htmlString = html.ToString(SaveOptions.DisableFormatting);
File.WriteAllText(htmlPath, htmlString, Encoding.UTF8);

```
OUTPUT
![image](https://user-images.githubusercontent.com/5969304/117657007-b89bc780-b1a1-11eb-935c-4fbcd8ed5e79.png)

----
Here is the code that I used before and that generates spaces:
```C#
string docxPath = @"test.docx";
string htmlPath = @"test.html";

using WordprocessingDocument wDoc = WordprocessingDocument.Open(docxPath, true);
HtmlConverterSettings htmlConverterSetting = new()
{
    CssClassPrefix = "pt-"
};
XElement htmlElement = HtmlConverter.ConvertToHtml(wDoc, htmlConverterSetting);

File.WriteAllText(htmlPath, htmlElement.ToStringNewLineOnAttributes(), Encoding.UTF8);

```

Looks like `WmlToHtmlConverter` had to be used instead of `HtmlConverter`. Actually, do not know the difference between them. Will learn later.
