### ISSUE TITLE
SixLabors.ImageSharp License check

### ISSUE THREAD

**Issue by sergey-tihon** [sergey-tihon/Clippit#68]
Hi @JimBobSquarePants

Thank you for all the amazing job done with `SixLabors.ImageSharp`. I personally love this library and level of the compatibility with `System.Drawing.*` libraries.

I am the maintainer of `Clippit` (fork of Open-Xml-PowerTools) that was migrated to `.NET 6` and `System.Drawing` layer replaced by `SixLabors.ImageSharp` libraries.

I would love to keep this library under `MIT` license and consume the latest versions of `ImageSharp`.

From what I see in [Six Labors Split License](https://github.com/SixLabors/ImageSharp/blob/main/LICENSE#L33C1-L36C68) it is perfectly legal to use case:

```
   Works in Source or Object form are licensed to You under the Apache License, Version 2.0 if.

   - You are consuming the Work in for use in software licensed under an Open Source or Source Available license.
   - You are consuming the Work as a Transitive Package Dependency.
```

I read it as that consumers of this library (who do not directly reference `SixLabors.ImageSharp`) can use it commercially *without* buying the Six Labors Commercial License.

*Can you please confirm that I understand it correctly?*

**Comment by JimBobSquarePants** [comment]
Hi @sergey-tihon 

Yes, you are understanding the license correctly. Under the terms of the Split License, the software is licensed to you under Apache 2.0.
