### ISSUE TITLE
DocumentAssembler: Text formatting?

### ISSUE THREAD

**Issue by Marcel0024** [sergey-tihon/Clippit#70]
I couldn't find a way to format text in the document assembler. rtf/markdown/html or anything? Am i correct in this?

I'm willing to take a stab at it, with some guidance, does it happen anywhere else in the library that i can look how it should be done?

With some formatting, like bold, italic, underline and list would make this killer library.

**Comment by sergey-tihon** [comment]
I do not know (because I do not use it much)

But I think that if the placeholder already has styles applied (like bold/italic/underline) then DocumentAssemblier should insert text and preserve styles. Is not it?

**Comment by Marcel0024** [comment]
Yes it does. But that's for the whole variable. I want to add a big paragraph and format the text myself. So a long text with bold/italic a few words.

**Comment by sergey-tihon** [comment]
How complicated is your template document? Maybe you can use `DocumentBuilder` API?

You can generate Word document with arbitrary formatting and then merge multiple documents into one using DocumentBuilder.

https://github.com/sergey-tihon/Clippit/blob/net6/Clippit.Tests/Word/DocumentBuilderTests.cs#L172-L189

**Comment by Marcel0024** [comment]
Nice suggestion, but I don't think it will work. My templates are quite complicated. Users fill in their profile and can generate a Word document out of it with the company styling. So, some paragraphs inside tables need some formatting by the users.

**Comment by sergey-tihon** [comment]
Then I probably have nothing to offer ... 

Maybe `HtmlToWmlConverter.ConvertHtmlToWml`? Generate HTML and convert it to  Word? (never used this part of the library myself)

**Comment by MalcolmJohnston** [comment]
I am looking for a suitable home for a number of improvements that I have made to OpenXmlPowerTools over the years.  One of the improvements is to support some inline formatting from HTML, including:

* Bold
* Underline
* Italic
* Hyperlinks

I would be happy to open a PR here if you have the time to review / merge it?

**Comment by sergey-tihon** [comment]
@MalcolmJohnston Sure, PRs are more than welcome, especially if they are relatively small, keep build green and ideally contain some tests 😀

**Comment by nefarius** [comment]
Ahoy folks, sorry to dig this up but I am trying to figure out if I found a bug or am misusing or misunderstanding the feature.

My Word Doc Template defines a Table of variable rows and fixed defined columns. My issue here is that I want to provide a string list as each line followed by a hard line break within the same cell and if I use the HTML tags they just get rendered verbatim. Is this supposed to work within a table cell too? Does a specific syntax need to be used within a table cell for it to format HTML tags correctly?

Thanks & cheers!

**Comment by nefarius** [comment]
Alright browsing the sources and also #86 I think I see the problem. The new HTML transformation code is only invoked on `Content` elements but not used anywhere when processing table cells. I'll dip my toes into the sources and see if I can tackle that 🫡
