### ISSUE TITLE
<EndImage /> produces "Schema Validation Error" error

### ISSUE THREAD

**Issue by IvanDrag0** [sergey-tihon/Clippit#78]
According to the image support [documentation](https://sergey-tihon.github.io/Clippit/tutorials/word/DocumentAssembler_ImagesSupport.html), to add an image using the DocumentAssembler, I need to use a text content control with the "Image" tag, followed by a blank picture content control, followed by a text content control with the text "<EndImage />".

When I try to do that, the resulting document renders the image, however, it also produces an error:

Template:

![image](https://github.com/user-attachments/assets/b077ab8d-31be-42be-b5f3-8bf2d12c45b5)

Result:

![image](https://github.com/user-attachments/assets/2030d689-0844-41a3-a656-58b7d884524c)

If I remove the "<EndImage />" content control, the image is rendered as expected without any errors. Is there a reason we need to add the "<EndImage />" content control? Or am I using it incorrectly?

**Comment by Marcel0024** [comment]
I believe the documentation is not correct. You don't need the <EndImage/> tag

This is working for me:
 
![image](https://github.com/user-attachments/assets/de9fdc6b-8b88-44b3-acb0-44a386cc7a3c)
